# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rw.Metropolis using Rcpp, in Ex1, Homework9
#' @description The function is for random walk Metropolis sampler to generate the standard Laplace distribution, which is written in Rcpp
#' @param sigma the standard deviation of the normal distribution
#' @param x0 the initial value of the chains
#' @param N the length of the chains
#' @return a matrix,include the value of each step, and the reject times
#' @export
rwMC <- function(sigma, x0, N) {
    .Call('_StatComp20025_rwMC', PACKAGE = 'StatComp20025', sigma, x0, N)
}

#' @title Runif using Rcpp, in Ex2, Homework9
#' @description The function is for randomly generating sample that are uniformly distributed on (0,1) with Rcpp
#' @param N the number of the sample
#' @return a vector of random sample
#' @export
GetRandomNumber <- function(N) {
    .Call('_StatComp20025_GetRandomNumber', PACKAGE = 'StatComp20025', N)
}

